### ISSUE TITLE
BasicTopLeftWall - is misshapen

### ISSUE THREAD

**Issue by Zirientis** [Zirientis/ap-cs-dungeoncrawler-msrl#1]
The BasicTopLeftWall looks funny and seems to be uneven.

**Comment by Zirientis** [comment]
This might apply to the other textures as well.

**Comment by 1piedude11** [comment]
Those textures are just for basic graphics testing, and are definitely far from perfect. Just ignore that for now, it will be fixed when we flesh out the graphics of the game.
